# Generated by Django 3.2.8 on 2021-10-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='descripction',
            new_name='description',
        ),
    ]
